<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DiscountCode;
use Carbon\Carbon;

class DiscountCodeSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();
        $adminId = 1; // id admin
        $codes = [
            [
                'code' => 'FREESHIP',
                'name' => 'Miễn phí vận chuyển',
                'description' => 'Áp dụng cho mọi đơn hàng từ 100K',
                'discount_type' => 'free_shipping',
                'discount_value' => 0,
                'min_requirement_type' => 'order_amount',
                'min_requirement_value' => 100000,
                'max_discount_amount' => null,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'public',
                'max_total_usage' => 1000,
                'max_usage_per_user' => 5,
                'start_date' => $now->copy()->subDays(5),
                'end_date' => $now->copy()->addMonths(2),
            ],
            [
                'code' => 'GIAM10K',
                'name' => 'Giảm 10.000đ cho đơn từ 50K',
                'description' => 'Áp dụng toàn hệ thống',
                'discount_type' => 'fixed_amount',
                'discount_value' => 10000,
                'min_requirement_type' => 'order_amount',
                'min_requirement_value' => 50000,
                'max_discount_amount' => null,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'public',
                'max_total_usage' => 500,
                'max_usage_per_user' => 2,
                'start_date' => $now->copy()->subDays(2),
                'end_date' => $now->copy()->addMonth(),
            ],
            [
                'code' => 'WELCOME',
                'name' => 'Chào mừng khách mới',
                'description' => 'Giảm 20% cho đơn đầu tiên',
                'discount_type' => 'percentage',
                'discount_value' => 20,
                'min_requirement_type' => null,
                'min_requirement_value' => null,
                'max_discount_amount' => 30000,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'personal',
                'max_total_usage' => 1,
                'max_usage_per_user' => 1,
                'start_date' => $now->copy()->subDays(1),
                'end_date' => $now->copy()->addMonths(3),
            ],
            [
                'code' => 'TET2024',
                'name' => 'Tết 2024 - Giảm 24%',
                'description' => 'Chỉ áp dụng dịp Tết',
                'discount_type' => 'percentage',
                'discount_value' => 24,
                'min_requirement_type' => 'order_amount',
                'min_requirement_value' => 200000,
                'max_discount_amount' => 50000,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'public',
                'max_total_usage' => 500,
                'max_usage_per_user' => 2,
                'start_date' => Carbon::create(2024, 2, 1),
                'end_date' => Carbon::create(2024, 2, 29),
            ],
            [
                'code' => 'SUMMER20',
                'name' => 'Hè rực rỡ - Giảm 20%',
                'description' => 'Áp dụng cho sản phẩm nước giải khát',
                'discount_type' => 'percentage',
                'discount_value' => 20,
                'min_requirement_type' => 'order_amount',
                'min_requirement_value' => 30000,
                'max_discount_amount' => 20000,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'specific_categories',
                'usage_type' => 'public',
                'max_total_usage' => 300,
                'max_usage_per_user' => 3,
                'start_date' => $now->copy()->addDays(10),
                'end_date' => $now->copy()->addMonths(2),
            ],
            [
                'code' => 'BLACKFRIDAY',
                'name' => 'Black Friday -50%',
                'description' => 'Giảm 50% cho mọi đơn hàng',
                'discount_type' => 'percentage',
                'discount_value' => 50,
                'min_requirement_type' => null,
                'min_requirement_value' => null,
                'max_discount_amount' => 100000,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'public',
                'max_total_usage' => 100,
                'max_usage_per_user' => 1,
                'start_date' => Carbon::create($now->year, 11, 24),
                'end_date' => Carbon::create($now->year, 11, 25),
            ],
            [
                'code' => 'XMAS',
                'name' => 'Noel 2024 - Giảm 30%',
                'description' => 'Áp dụng cho đơn từ 150K',
                'discount_type' => 'percentage',
                'discount_value' => 30,
                'min_requirement_type' => 'order_amount',
                'min_requirement_value' => 150000,
                'max_discount_amount' => 40000,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'public',
                'max_total_usage' => 200,
                'max_usage_per_user' => 2,
                'start_date' => Carbon::create($now->year, 12, 20),
                'end_date' => Carbon::create($now->year, 12, 27),
            ],
            [
                'code' => 'NEWUSER',
                'name' => 'Ưu đãi khách hàng mới',
                'description' => 'Giảm 15K cho đơn đầu tiên',
                'discount_type' => 'fixed_amount',
                'discount_value' => 15000,
                'min_requirement_type' => null,
                'min_requirement_value' => null,
                'max_discount_amount' => null,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'personal',
                'max_total_usage' => 1,
                'max_usage_per_user' => 1,
                'start_date' => $now->copy()->subDays(3),
                'end_date' => $now->copy()->addMonths(6),
            ],
            [
                'code' => 'HOTDEAL',
                'name' => 'Hot Deal 30K',
                'description' => 'Giảm 30K cho đơn từ 200K',
                'discount_type' => 'fixed_amount',
                'discount_value' => 30000,
                'min_requirement_type' => 'order_amount',
                'min_requirement_value' => 200000,
                'max_discount_amount' => null,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'public',
                'max_total_usage' => 100,
                'max_usage_per_user' => 1,
                'start_date' => $now->copy()->addDays(5),
                'end_date' => $now->copy()->addMonths(1),
            ],
            [
                'code' => 'LUNCH10',
                'name' => 'Giảm 10% giờ trưa',
                'description' => 'Áp dụng 11h-13h mỗi ngày',
                'discount_type' => 'percentage',
                'discount_value' => 10,
                'min_requirement_type' => null,
                'min_requirement_value' => null,
                'max_discount_amount' => 20000,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'public',
                'max_total_usage' => 300,
                'max_usage_per_user' => 2,
                'valid_from_time' => '11:00:00',
                'valid_to_time' => '13:00:00',
                'start_date' => $now->copy()->subDays(1),
                'end_date' => $now->copy()->addMonths(1),
            ],
            [
                'code' => 'DINNER15',
                'name' => 'Giảm 15% giờ tối',
                'description' => 'Áp dụng 18h-21h mỗi ngày',
                'discount_type' => 'percentage',
                'discount_value' => 15,
                'min_requirement_type' => null,
                'min_requirement_value' => null,
                'max_discount_amount' => 25000,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'public',
                'max_total_usage' => 200,
                'max_usage_per_user' => 2,
                'valid_from_time' => '18:00:00',
                'valid_to_time' => '21:00:00',
                'start_date' => $now->copy()->subDays(1),
                'end_date' => $now->copy()->addMonths(1),
            ],
            [
                'code' => 'WEEKEND',
                'name' => 'Ưu đãi cuối tuần',
                'description' => 'Chỉ áp dụng thứ 7, CN',
                'discount_type' => 'percentage',
                'discount_value' => 12,
                'min_requirement_type' => null,
                'min_requirement_value' => null,
                'max_discount_amount' => 15000,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'public',
                'max_total_usage' => 400,
                'max_usage_per_user' => 2,
                'valid_days_of_week' => json_encode([6,0]),
                'start_date' => $now->copy()->addDays(2),
                'end_date' => $now->copy()->addMonths(2),
            ],
            [
                'code' => 'COMBO50K',
                'name' => 'Combo giảm 50K',
                'description' => 'Áp dụng cho combo đặc biệt',
                'discount_type' => 'fixed_amount',
                'discount_value' => 50000,
                'min_requirement_type' => 'order_amount',
                'min_requirement_value' => 300000,
                'max_discount_amount' => null,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'specific_combos',
                'usage_type' => 'public',
                'max_total_usage' => 100,
                'max_usage_per_user' => 1,
                'start_date' => $now->copy()->addDays(1),
                'end_date' => $now->copy()->addMonths(1),
            ],
            [
                'code' => 'BRANCHHN',
                'name' => 'Hà Nội giảm 20%',
                'description' => 'Chỉ áp dụng chi nhánh Hà Nội',
                'discount_type' => 'percentage',
                'discount_value' => 20,
                'min_requirement_type' => null,
                'min_requirement_value' => null,
                'max_discount_amount' => 30000,
                'applicable_scope' => 'specific_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'public',
                'max_total_usage' => 100,
                'max_usage_per_user' => 2,
                'start_date' => $now->copy()->addDays(1),
                'end_date' => $now->copy()->addMonths(1),
            ],
            [
                'code' => 'BRANCHHCM',
                'name' => 'HCM giảm 15%',
                'description' => 'Chỉ áp dụng chi nhánh HCM',
                'discount_type' => 'percentage',
                'discount_value' => 15,
                'min_requirement_type' => null,
                'min_requirement_value' => null,
                'max_discount_amount' => 25000,
                'applicable_scope' => 'specific_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'public',
                'max_total_usage' => 100,
                'max_usage_per_user' => 2,
                'start_date' => $now->copy()->addDays(1),
                'end_date' => $now->copy()->addMonths(1),
            ],
            [
                'code' => 'STUDENT',
                'name' => 'Sinh viên giảm 10%',
                'description' => 'Áp dụng cho khách hàng có thẻ SV',
                'discount_type' => 'percentage',
                'discount_value' => 10,
                'min_requirement_type' => null,
                'min_requirement_value' => null,
                'max_discount_amount' => 10000,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'personal',
                'max_total_usage' => 200,
                'max_usage_per_user' => 2,
                'start_date' => $now->copy()->addDays(1),
                'end_date' => $now->copy()->addMonths(2),
            ],
            [
                'code' => 'VIP30',
                'name' => 'VIP giảm 30%',
                'description' => 'Chỉ dành cho khách VIP',
                'discount_type' => 'percentage',
                'discount_value' => 30,
                'min_requirement_type' => null,
                'min_requirement_value' => null,
                'max_discount_amount' => 50000,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'personal',
                'max_total_usage' => 50,
                'max_usage_per_user' => 1,
                'start_date' => $now->copy()->addDays(1),
                'end_date' => $now->copy()->addMonths(2),
            ],
            [
                'code' => 'BIRTHDAY',
                'name' => 'Sinh nhật giảm 50K',
                'description' => 'Áp dụng cho khách sinh nhật tháng này',
                'discount_type' => 'fixed_amount',
                'discount_value' => 50000,
                'min_requirement_type' => 'order_amount',
                'min_requirement_value' => 100000,
                'max_discount_amount' => null,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'personal',
                'max_total_usage' => 100,
                'max_usage_per_user' => 1,
                'start_date' => $now->copy()->addDays(1),
                'end_date' => $now->copy()->addMonths(2),
            ],
            [
                'code' => 'LOYALTY',
                'name' => 'Khách thân thiết giảm 20%',
                'description' => 'Chỉ dành cho khách hàng thân thiết',
                'discount_type' => 'percentage',
                'discount_value' => 20,
                'min_requirement_type' => null,
                'min_requirement_value' => null,
                'max_discount_amount' => 30000,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'personal',
                'max_total_usage' => 100,
                'max_usage_per_user' => 2,
                'start_date' => $now->copy()->addDays(1),
                'end_date' => $now->copy()->addMonths(2),
            ],
            [
                'code' => 'FLASHSALE',
                'name' => 'Flash Sale 40%',
                'description' => 'Giảm 40% trong 2 ngày',
                'discount_type' => 'percentage',
                'discount_value' => 40,
                'min_requirement_type' => null,
                'min_requirement_value' => null,
                'max_discount_amount' => 40000,
                'applicable_scope' => 'all_branches',
                'applicable_items' => 'all_items',
                'usage_type' => 'public',
                'max_total_usage' => 50,
                'max_usage_per_user' => 1,
                'start_date' => $now->copy()->addDays(1),
                'end_date' => $now->copy()->addDays(3),
            ],
        ];

        foreach ($codes as $i => $data) {
            // Idempotent seeding: cập nhật nếu đã tồn tại theo code, tạo mới nếu chưa có
            DiscountCode::updateOrCreate(
                ['code' => $data['code']],
                array_merge([
                    'image' => null,
                    'applicable_ranks' => null,
                    'rank_exclusive' => false,
                    'valid_days_of_week' => null,
                    'is_active' => true,
                    'is_featured' => $i < 5, // 5 mã đầu nổi bật
                    'display_order' => $i + 1,
                    'created_by' => $adminId,
                    'current_usage_count' => 0,
                ], $data)
            );
        }
    }
}